### ISSUE TITLE
Build error Guitarix on OS X

### ISSUE THREAD

**Issue by JonathanCooper** [brummer10/guitarix#16]
I'm trying to build Guitarix on OS X 10.14.5.  Does anyone know if this has been done or is expected to work?  I know the project doesn't explicitly support non-linux platforms, just wondering if it has been done.

For my actual error, from `./waf build`:

```
../src/headers/gx_system.h:135:12: error: cannot initialize a parameter of type 'void **' with an rvalue of type 'typeof ((oldv)) *' (aka '_jack_session_event **')
````

Any ideas?

**Comment by brummer10** [comment]
Hi
Someone has build guitarix on OS X some years ago, and we've implemented some patches from that, so that rudimental support for OS X is included. But I've no idea if guitarix as of today will work on OS X. 

To your actual error, which version of guitarix do you try? 
To get some assistance here you should try the version from git.
I guess a type cast will help for the error, but my gx_system.h seems to differ from the version you try, as my line 135 have nothing to do with jack_session_event.

**Comment by JonathanCooper** [comment]
Hi @brummer10!  I was using the version checked out by `git clone http://git.code.sf.net/p/guitarix/git guitarix`.

I actually got past that error by changing the line from:
```
return g_atomic_pointer_compare_and_exchange(reinterpret_cast<void* volatile*>(p), oldv, newv);
```
to
```
return g_atomic_pointer_compare_and_exchange(reinterpret_cast<void* volatile*>(p), (void*)oldv, newv);
```

So we can close this issue.  I've run into other issues (mostly that OS X `ld` doesn't support `-z` flag), but I think I have a path forward on those for now!  I'll open a new issue if necessary.

**Comment by brummer10** [comment]
Ah, okay. I've implement that into the source right now.
