### ISSUE TITLE
Deleting an effect from a preset don´t delete the assigned MIDI Control.

### ISSUE THREAD

**Issue by fernando-inf** [brummer10/guitarix#80]
Deleting an effect from a preset don´t delete the assigned MIDI Control. I believe this causes that when changing presets, the MIDI CC continues to be sent to the MIDI Out and this causes an infinite loop of MIDI message inputs and outputs. This happens if MIDI Thru is used in the PEDALBOARD.
MIDI Thru is necessary, since Guitarix don´t take MIDI OUT signals as MIDI IN signals by itself.

**Comment by brummer10** [comment]
Hi

When you switch a preset, guitarix send midi feedback for all connected controllers to allow to sync all used midi controllers with the state of guitarix. This sync should be done without that the midi controller send messages back to guitarix. (feedback mode)
Surely we don't delete a connected controller just because you put it out of the rack, you may later put it back in the rack and use it again. If you would delete a controller connection you've to do it by yourself.

**Comment by fernando-inf** [comment]
Hello, I understand your position. But I have found that by activating "`Send Midi feddback`" in Guitarix, the presets are updated correctly only if Guitarix they receive a MIDI signal. I raised that problem in this forum:

https://www.reddit.com/r/Guitarix/comments/onm96e/comportamiento_err%C3%B3neo_en_el_cambio_de_preset_al/

But apparently I haven't been able to explain myself properly yet.

**Comment by brummer10** [comment]
Yea, I'm the same person then in the forum. 
What I understand is that you've build and wrote your MIDI controller by yourself. 
What I mean is, that when your MIDI controller receive a MIDI feedback message from guitarix, it should set it's sate (set a LED on/off, etc.) without send a MIDI message back to guitarix. Otherwise you'll indeed end up in a feedback loop. But that will happen independent from if the connected controller is active in the rack or not.

**Comment by fernando-inf** [comment]
This issue is no longer an imminent danger, as the bug in the presets update in Issue # 85 has been fixed. I proceed to close it for now.
